language: python

services:
  - docker

jobs:
  include:
    - stage: build docker image
      script:
      - export VERSION=$TRAVIS_BUILD_ID
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build --build-arg VERSION=$VERSION -t curl-action:$VERSION -f Dockerfile .
      - docker images
      - docker tag curl-action:$VERSION $DOCKER_USERNAME/curl-action:$VERSION
      - docker tag curl-action:$VERSION $DOCKER_USERNAME/curl-action:latest
      - docker tag curl-action:$VERSION $DOCKER_USERNAME/curl-action
      - docker push $DOCKER_USERNAME/curl-action:$VERSION
      - docker push $DOCKER_USERNAME/curl-action:latest
      - docker push $DOCKER_USERNAME/curl-action
